Example Models SSS 3 and SSS 4
arup-group/gofer-examples pull request #17
Opened 2023-05-11 16:56 UTC by elizabethcbailey

2023-05-18 14:21 UTC, Alvaro-Rodrigueez commented on validation/SSS 3/model.json
> +        "owner": "e94fedd3-c151-5d43-ad8b-3d78cb48bbce",
Could you change the owner to be "710fe8da-8cb3-41c1-807b-13e20e0a59d1" that's the special owner for all the example models

2023-05-18 14:21 UTC, Alvaro-Rodrigueez requested changes
SSS 4 only has the image, all other files are empty

2023-05-25 09:43 UTC, Alvaro-Rodrigueez approved these changes

2023-05-25 09:44 UTC, elizabethcbailey commented
image for SSS 4 deleted.

2023-05-25 09:45 UTC, elizabethcbailey commented on validation/SSS 3/model.json
> +        "owner": "e94fedd3-c151-5d43-ad8b-3d78cb48bbce",
Owner udpated.

2023-05-25 09:46 UTC, merged